name: Dependabot

on:
  pull_request:
    branches:
      - "dependabot/**"

permissions:
  pull-requests: write
  contents: write

jobs:
  Auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
          use-github-auto-merge: true
