name: Dependabot
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  Auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          github-token: ${{ secrets.ghrs_github_api_token }}
          use-github-auto-merge: true
